apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-{deploymentEnv}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-{deploymentEnv}
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
