kind: Service
apiVersion: v1
metadata:
  name: images-staging
spec:
  selector:
    app: images-staging
  type: LoadBalancer
  externalIPs:
  ports:
  - port: 3000
    targetPort: 9292
    name: main-port
    protocol: TCP
